### ISSUE TITLE
licenses is missing `identifier`

### ISSUE THREAD

**Issue by ahmednfwela** [meilisearch/open-api#15]
current:
```yaml
license:
  name: MIT
```

should be:
```yaml
license:
  name: MIT
  identifier: MIT
```
