### ISSUE TITLE
all `operationId`s MUST be unique across documents

### ISSUE THREAD

**Issue by ahmednfwela** [meilisearch/open-api#16]
current:
```yaml
"/indexes/{indexUid}/settings/non-separator-tokens":
    get:
      # ....
      operationId: get
```
should be (for example):
```yaml
"/indexes/{indexUid}/settings/non-separator-tokens":
    get:
      # ....
      operationId: getIndexSettingsNonSeparatorTokens
```
